# config context path to "/" by setting an empty string
server:
  contextPath: /

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

security:
  header: Authorization
  secret: 4616f295-a89a-4e85-a308-9f8f43633147
  expiration: 604800
  route:
    authentication:
      login: login
      refresh: refresh
      signup: signup
      confirm: confirm
      verify: verify
    userDetails:
      isEmailRegistered: isEmailRegistered
      getUserDetails: getUserDetails
      updateUserDetails: updateUserDetails
      changeEmail: changeEmail
      changePassword: changePassword
    account:
      deleteAccount: deleteAccount
      reviveUser: reviveUser

general:
  path: general
  route:
    getGeneralChartSelectionsList: getGeneralChartSelectionsList
    getUserChartSelectionsList: getUserChartSelectionsList
    getDefaultDataTable: getDefaultDataTable
    getGeneralDataTable: getGeneralDataTable
    getVersion: getVersion
    getLanguages: getLanguages
    getCurrencies: getCurrencies

user:
  path: user
  route:
    getCategoriesList: getCategoriesList
    getUserDefaultDataTable: getUserDefaultDataTable
    getUserDataTable: getUserDataTable
    addRecord: addRecord
    addCustomCategory: addCustomCategory
    getRecordsList: getRecordsList
    deleteRecord: deleteRecord
    editRecord: editRecord

#logging:
#  level:
#    org.springframework:
#      security: DEBUG