# config context path to "/" by setting an empty string
server:
  contextPath: /kamabizbazti

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

security:
  header: Authorization
  secret: 4616f295-a89a-4e85-a308-9f8f43633147
  expiration: 604800
  route:
    authentication:
      login: login
      refresh: refresh
      signup: signup

general:
  path: general
  route:
    getGeneralChartSelectionsList: getGeneralChartSelectionsList
    getUserChartSelectionsList: getUserChartSelectionsList
    getDefaultDataTable: getDefaultDataTable
    getGeneralDataTable: getGeneralDataTable

user:
  path: user
  route:
    getPurposesList: getPurposesList
    getUserDefaultDataTable: getUserDefaultDataTable
    getUserDataTable: getUserDataTable
    addRecord: addRecord
    addCustomPurpose: addCustomPurpose
    getRecordsList: getRecordsList
    deleteRecord: deleteRecord
    editRecord: editRecord

#logging:
#  level:
#    org.springframework:
#      security: DEBUG